services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
     - db:/var/lib/postgresql/data
    networks:
      - networkParking
  parking:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - networkParking

volumes:
  db: 
  
networks:
  networkParking:
